name: BA-IFSS
channels:
  - defaults
  - conda-forge
dependencies:
-python=3.9
-pip=22.2.2
-pip:
  -jupyter==1.0.0
  -Keras==2.10.0
  -matplotlib==3.6.1
  -numpy==1.23.4
  -opencv-contrib-python==4.6.0.66
  -openpyxl==3.0.10
  -pandas==1.5.1
  -Pillow==9.2.0
  -pre-commit==2.17.0
  -scikit-image==0.19.3
  -scikit-learn==1.1.2
  -sewar==0.4.5
  -tensorflow-macos==2.10.0
  -tqdm==4.64.1
  -shapely=2.06
  -medpy=0.5.2
  -poetry=1.8.4
  -tensorflow-addons=0.22.0
  -scipy=1.14.1
  -imageio=2.36.1
  -pynrrd=1.1.1
  -h5py=3.12.1
  
